/******************************************************************************
 *
 * FILE:
 *      audio_playback.h
 *
 * DESCRIPTION:
 *      Audio playback coordination module for the e-PA firmware.
 *
 * PURPOSE:
 *      Provides a unified interface for reminder audio playback.
 *
 *      The Audio Playback module coordinates playback requests,
 *      playback lifecycle management, playback completion reporting,
 *      and playback error handling.
 *
 *      This module does not generate audio content. It consumes
 *      playback sequences generated by the speech composition layer.
 *
 * RESPONSIBILITIES:
 *      - Start playback
 *      - Stop playback
 *      - Pause playback (future)
 *      - Track playback state
 *      - Report playback completion
 *      - Report playback failures
 *
 * ARCHITECTURAL ROLE:
 *      Application Layer
 *
 * DESIGN PATTERNS:
 *      - Media Controller Pattern
 *      - State Machine Pattern
 *
 * COLLABORATORS:
 *      - reminder_runtime
 *      - speech_composer
 *      - audio_output
 *      - event_dispatcher
 *
 * OWNERSHIP RULES:
 *      - Owns playback lifecycle.
 *      - Owns playback state.
 *      - Does not own reminder lifecycle.
 *      - Does not own audio asset generation.
 *
 * MEMORY STRATEGY:
 *      - Static allocation only.
 *      - Fixed playback sequence limits.
 *
 * TESTING CONSIDERATIONS:
 *      - Playback start
 *      - Playback completion
 *      - Playback failure
 *      - Playback stop
 *      - Invalid sequence handling
 *      - Concurrent playback requests
 *
 ******************************************************************************/

#ifndef AUDIO_PLAYBACK_H
#define AUDIO_PLAYBACK_H

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include <stdbool.h>

/******************************************************************************
 * CONFIGURATION
 ******************************************************************************/

#define AUDIO_PLAYBACK_MAX_SEGMENTS      (32U)

/******************************************************************************
 * PLAYBACK STATE
 ******************************************************************************/

typedef enum
{
    AUDIO_PLAYBACK_STATE_IDLE = 0,

    AUDIO_PLAYBACK_STATE_PLAYING,

    AUDIO_PLAYBACK_STATE_STOPPED,

    AUDIO_PLAYBACK_STATE_ERROR

} audio_playback_state_t;

/******************************************************************************
 * AUDIO ASSET IDENTIFIER
 ******************************************************************************/

typedef uint16_t audio_asset_id_t;

/******************************************************************************
 * AUDIO SEGMENT
 ******************************************************************************/

typedef struct
{
    audio_asset_id_t asset_id;

} audio_segment_t;

/******************************************************************************
 * PLAYBACK SEQUENCE
 ******************************************************************************/

typedef struct
{
    audio_segment_t segments[AUDIO_PLAYBACK_MAX_SEGMENTS];

    uint16_t segment_count;

} audio_sequence_t;

/******************************************************************************
 * PLAYBACK RESULT
 ******************************************************************************/

typedef enum
{
    AUDIO_PLAYBACK_OK = 0,

    AUDIO_PLAYBACK_INVALID_SEQUENCE,

    AUDIO_PLAYBACK_BUSY,

    AUDIO_PLAYBACK_ERROR

} audio_playback_result_t;

/******************************************************************************
 * MODULE INITIALIZATION
 ******************************************************************************/

/**
 * Initialize audio playback subsystem.
 */
void audio_playback_init(void);

/******************************************************************************
 * PLAYBACK CONTROL
 ******************************************************************************/

/**
 * Start playback.
 */
audio_playback_result_t audio_playback_start(
    const audio_sequence_t *sequence);

/**
 * Stop playback.
 */
bool audio_playback_stop(void);

/**
 * Abort playback immediately.
 */
bool audio_playback_abort(void);

/******************************************************************************
 * PLAYBACK STATUS
 ******************************************************************************/

/**
 * Get playback state.
 */
audio_playback_state_t audio_playback_get_state(void);

/**
 * Returns true if playback active.
 */
bool audio_playback_is_active(void);

/**
 * Returns current playback position.
 */
uint16_t audio_playback_current_segment(void);

/******************************************************************************
 * RUNTIME PROCESSING
 ******************************************************************************/

/**
 * Runtime processing function.
 */
void audio_playback_process(void);

/******************************************************************************
 * EVENT HANDLING
 ******************************************************************************/

/**
 * Event dispatcher callback.
 */
void audio_playback_event_handler(
    const void *event);

/******************************************************************************
 * DIAGNOSTICS
 ******************************************************************************/

/**
 * Total playback requests.
 */
uint32_t audio_playback_request_count(void);

/**
 * Successful playbacks.
 */
uint32_t audio_playback_success_count(void);

/**
 * Playback failures.
 */
uint32_t audio_playback_failure_count(void);

/**
 * Playback aborts.
 */
uint32_t audio_playback_abort_count(void);

/******************************************************************************
 * REFERENCE WORKFLOW
 *
 * Reminder Runtime
 *      ->
 * Playback Request
 *
 * Audio Playback
 *      ->
 * PLAYBACK_STARTED
 *
 * Audio Playback
 *      ->
 * PLAYBACK_COMPLETED
 *
 * OR
 *
 * Audio Playback
 *      ->
 * PLAYBACK_FAILED
 *
 ******************************************************************************/

#ifdef __cplusplus
}
#endif

#endif /* AUDIO_PLAYBACK_H */
